### ISSUE TITLE
Broker fails to serialize fa_file record

### ISSUE THREAD

**Issue by Olerdrive** [zeek/broker#43]
Tried to use Broker to extract files and pass them to python script without saving it to disk, so I added `Files::ANALYZER_DATA_EVENT` analyzer with stream event, in which I publish extracted data and `fa_file` to some topic `/files`.

```
event manager_data_event(f: fa_file, data: string)
    {
        Broker::publish("/files", manager_data_event, f, data);
    }

event worker_data_event(f: fa_file, data: string)
    {
        Broker::publish(Cluster::manager_topic, manager_data_event, f, data);
    }

event file_sniff(f: fa_file, meta: fa_metadata)
    {
        Files::add_analyzer(f, Files::ANALYZER_DATA_EVENT, [$stream_event=worker_data_event]);
    }
```

And my python subscriber script:
``` 
ep = broker.Endpoint()
sub = ep.make_subscriber("/files")
ss = ep.make_status_subscriber(True)
ep.peer(BC_ADDR, BC_PORT)
st = ss.get()

while True:
    (t, d) = sub.get()
     .....
```

fails with the following:
```
Traceback (most recent call last):
  File "./script.py", line 203, in <module>
    (t, d) = sub.get()
  File "/usr/lib/python3/dist-packages/broker/__init__.py", line 100, in get
    return (msg[0].string(), Data.to_py(msg[1]))
  File "/usr/lib/python3/dist-packages/broker/__init__.py", line 456, in to_py
    return converters[d.get_type()]()
  File "/usr/lib/python3/dist-packages/broker/__init__.py", line 452, in <lambda>
    Data.Type.Vector: lambda: to_vector(d.as_vector())
  File "/usr/lib/python3/dist-packages/broker/__init__.py", line 429, in to_vector
    return [Data.to_py(i) for i in v]
  File "/usr/lib/python3/dist-packages/broker/__init__.py", line 429, in <listcomp>
    return [Data.to_py(i) for i in v]
  File "/usr/lib/python3/dist-packages/broker/__init__.py", line 456, in to_py
    return converters[d.get_type()]()
  File "/usr/lib/python3/dist-packages/broker/__init__.py", line 452, in <lambda>
    Data.Type.Vector: lambda: to_vector(d.as_vector())
  File "/usr/lib/python3/dist-packages/broker/__init__.py", line 429, in to_vector
    return [Data.to_py(i) for i in v]
  File "/usr/lib/python3/dist-packages/broker/__init__.py", line 429, in <listcomp>
    return [Data.to_py(i) for i in v]
  File "/usr/lib/python3/dist-packages/broker/__init__.py", line 456, in to_py
    return converters[d.get_type()]()
  File "/usr/lib/python3/dist-packages/broker/__init__.py", line 452, in <lambda>
    Data.Type.Vector: lambda: to_vector(d.as_vector())
  File "/usr/lib/python3/dist-packages/broker/__init__.py", line 429, in to_vector
    return [Data.to_py(i) for i in v]
  File "/usr/lib/python3/dist-packages/broker/__init__.py", line 429, in <listcomp>
    return [Data.to_py(i) for i in v]
  File "/usr/lib/python3/dist-packages/broker/__init__.py", line 456, in to_py
    return converters[d.get_type()]()
  File "/usr/lib/python3/dist-packages/broker/__init__.py", line 452, in <lambda>
    Data.Type.Vector: lambda: to_vector(d.as_vector())
  File "/usr/lib/python3/dist-packages/broker/__init__.py", line 429, in to_vector
    return [Data.to_py(i) for i in v]
  File "/usr/lib/python3/dist-packages/broker/__init__.py", line 429, in <listcomp>
    return [Data.to_py(i) for i in v]
  File "/usr/lib/python3/dist-packages/broker/__init__.py", line 456, in to_py
    return converters[d.get_type()]()
  File "/usr/lib/python3/dist-packages/broker/__init__.py", line 449, in <lambda>
    Data.Type.Table: lambda: to_table(d.as_table()),
  File "/usr/lib/python3/dist-packages/broker/__init__.py", line 426, in to_table
    return {Data.to_py(k): Data.to_py(v) for (k, v) in t.items()}
  File "/usr/lib/python3/dist-packages/broker/__init__.py", line 426, in <dictcomp>
    return {Data.to_py(k): Data.to_py(v) for (k, v) in t.items()}
TypeError: unhashable type: 'list'
```

Passing any other arguments works correct, including passing only data without fa_file. 

Also probably any struct and record should be converted to Python dict?

**Comment by jsiwek** [comment]
Thanks for the report, this should be fixed in `master` now.

We can't convert Zeek records to Python dict because Broker does not transmit field names (it's not strictly required to interpret the data and adds extra overhead).

The underlying problem here was that records were converted to Python lists, which can't be used as an index to a dictionary: we do convert Zeek tables to dictionary and we need to be able to represent a table indexed by records.

In this case, the `fa_file` record contains a `table[conn_id] of connection` field, with `conn_id` being a record.

Even with this fixed, I'd generally suggest not sending things that have a full `connection` record in them: they can grow fairly large and contain a bunch of internal/miscellaneous state that you may not need.  Instead, I'd pick-and-choose the minimal set of data you are interested in and transmit just that if you can.
